### ISSUE TITLE
Preferred voices for languages

### ISSUE THREAD

**Issue by willwade** [AceCentre/TextAloud#21]
We have users who are multilingual

They will enter text using, say an English keyboard, play that, clear it, then switch keyboards (using the globe icon) - and then Write in their other language - e.g. Gujariti. Right now they would have to go into settings - change the voice - in between changing keyboards. That is  messy. 

So what we need to do is, depending on the keyboard they enter the text with automatically change the voice to the preferred language. Can we do this?

Plus have a way of setting preferred languages.

**Comment by willwade** [comment]
https://stackoverflow.com/questions/1414876/detecting-current-iphone-input-language

**Comment by willwade** [comment]
This is tricky to get right UI wise. @gavinhenderson - do you have any suggestions on how to do this? 

I think we need to merge voices under each language for a start #20 - and then somehow set a preferred voice/and default voice

**Comment by gavinhenderson** [comment]
This is a tricky one indeed. 

The main problem I see is that we would have to remember exactly which text was entered using which keyboard language. Because we can't base it off the language the keyboard is in at the time of 'speaking' because they probably will just be the default. Because they might type it all out in say french, switch to messenger and type in english, switch back to TextAloud then press play. But despite it being written in french if we use the 'current' keyboard when they press 'play' it will be spoken in english.

So we would need meta data on every word typed to store which language it was written in. This seems tricky and prone to breaking

It also gets a bit tricky because if they copy paste text in (or import) then we wont know what language it was written in

Alternatively, I think we can take a less 'smart' approach and have 'switch voice hotkeys'. So we allow a user to select their 5 favourite voices (across any language they want). Then we add 5 hot keys on the main screen of the app so they can switch to a favourite voice whilst in the 'presenting' mode. 

This also has the added benefit of allowing people to change which voice they are using (within the same language) to trial different voices.

**Comment by willwade** [comment]
so - the way you detect the language is via the keyboard - you can see what lang is being typed. So in a way - its relatively straightforward to see the language. The difficulty is how you set a preferred lang.

Here's my thoughts.

In voice picker. We have each voice - from what ever provider - in a list ordered by language. 
Then next to each voice is a toggle. Only one can toggle can be on per language. This toggle is for **preffered voice**.  Now  if you only choose one language - we just need a main or master voice - I cant work that bit out!
